### ISSUE TITLE
Installing bgem inside flow123d docker container - missing dependencies.

### ISSUE THREAD

**Issue by Paulie14** [GeoMop/bgem#49]
When creating venv, being inside containter (https://hub.docker.com/r/flow123d/geomop/tags) and installing bgem from source
```
pip install -e bgem
```
I need to install
```
pip install pybind11 # for bih
pip install attrs # for bgem
```
Should be these dependencies added to setup.py?

**Comment by Paulie14** [comment]
What is the purpose of `requirements.txt` and is it up to date?
When opening project in PyCharm , it found this file and created virtual environment automatically, but it is missing `gmsh`.

**Comment by jbrezmorf** [comment]
`requirements.txt` are for the development environment, package dependencies are in `setup.py`.

`pybind11`  is dependency of `bih`, `attrs` was missing but is probably part of dependencies in other packages since 
[tests](https://github.com/GeoMop/bgem/actions/runs/1892710007) runs fine for master branch.

There must be some peculiarities of the source install. Try:
`pip install -e <path to bgem sources>`

**Comment by jbrezmorf** [comment]
seems this work fine now. closing.
